default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  # prettier - multi formatter for .json, .yml, and .md files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@^3.2.4"
  # docformatter - PEP 257 compliant docstring formatter
  - repo: https://github.com/s-weigand/docformatter
    rev: 886a0329b3949dfb8be9f10f80bc96829923debe
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
